name: Builds, tests & co

on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install npm packages
        run: npm ci

      - name: Test source is well-formatted
        run: yarn fmt:check

      - name: Run the unit tests
        run: npm run test
